services:
  - type: web
    name: forensic-ai-soc
    runtime: docker
    rootDir: .
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: '*'
      - key: PYTHONUNBUFFERED
        value: 1
      - key: NVIDIA_API_KEY
        value: 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
      - key: NVIDIA_BASE_URL
        value: https://integrate.api.nvidia.com/v1
      - key: NVIDIA_MODEL
        value: meta/llama-3.1-8b-instruct
